config/routes.rb
Rails.application.routes.draw do
  resources :add_ons
  resources :products
  resources :menus
end

app/models/add_on.rb
class AddOn < ActiveRecord::Base
  extend PublishHelper
  
  has_many :additions
  has_many :add_ons, :through => :additions
  
  validates :name, :presence => true
end

app/models/addition.rb
class Addition < ActiveRecord::Base
  belongs_to :product
  belongs_to :add_on
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  extend PublishHelper

  use_farm_slugs
  
  use_open_close
  
  validates :name, :presence => true
  
  has_many :sections, :dependent => :destroy
  accepts_nested_attributes_for :sections, :allow_destroy => true, :reject_if => :section_is_invalid?
  
  private
  
  def section_is_invalid?(s)
    s['name'].blank?
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend PublishHelper
  
  default_scope{ order(:order) }
  
  belongs_to :section
  
  validates :name, :presence => true
  
  use_farm_slugs
  
  has_many :additions
  has_many :add_ons, :through => :additions
end

app/models/section.rb
class Section < ActiveRecord::Base
  extend PublishHelper  
  
  default_scope{ order(:order) }
  
  belongs_to :menu
    
  validates :name, :presence => true
  
  has_many :products, :dependent => :destroy
  accepts_nested_attributes_for :products, :reject_if => :product_is_invalid?, :allow_destroy => true
  
  use_farm_slugs
  
  private
  
  def product_is_invalid?(attrs)
    attrs[:name].blank?
  end
end

app/controllers/add_ons_controller.rb
class AddOnsController < ApplicationController
  before_action :set_add_on, only: [:show, :edit, :update, :destroy]

  # GET /add_ons
  def index
    @add_ons = AddOn.all
  end

  # GET /add_ons/1
  def show
  end

  # GET /add_ons/new
  def new
    @add_on = AddOn.new
  end

  # GET /add_ons/1/edit
  def edit
  end

  # POST /add_ons
  def create
    @add_on = AddOn.new(add_on_params)

    if @add_on.save
      redirect_to @add_on, notice: 'Add on was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /add_ons/1
  def update
    if @add_on.update(add_on_params)
      redirect_to @add_on, notice: 'Add on was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /add_ons/1
  def destroy
    @add_on.destroy
    redirect_to add_ons_url, notice: 'Add on was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_on
      @add_on = AddOn.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def add_on_params
      params.require(:add_on).permit(:name, :price, :published)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # include MenusControllerHelper
    # def self.included(klass)
    # klass.instance_eval do 
      before_action :set_menu, only: [:show, :edit, :update, :destroy]      
    # end
  # end
  
  def index
    set_menus_for_index
  end
  
  def show
    set_menu_for_show
  end
  
  def new
    @menu = Menu.new
    @menu.sections.build 
    @menu.sections.last.products.build
  end

  def edit
    @menu.sections.build
    @menu.sections.last.products.build
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      redirect_to @menu, notice: 'Menu was successfully created.'
    else
      render :new
    end
  end

  def update
    if @menu.update(menu_params)
      redirect_to @menu, notice: 'Menu was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @menu.destroy
    redirect_to menus_url, notice: 'Menu was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def menu_params
      params.require(:menu).permit(:name, :description, :published,
                                   :sections_attributes => [:name, :description, :published, :order, :_destroy, :id,
                                                            :products_attributes => [:name, :description, :published, 
                                                                                     :order, :id, :_destroy, :price,
                                                                                     :available]])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :section_id, :published, :slug)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
  def embedded_sections_form(form_builder)
    render :partial => 'sections/embedded_form', :locals => {:form_builder => form_builder}
  end
  
  def embedded_products_form(form_builder)
    render :partial => 'products/embedded_form', :locals => {:form_builder => form_builder}
  end
  
  def error_messages(record)
    render :partial => 'parts/error_messages', :locals => {:record => record}
  end
end

app/helpers/publish_helper.rb
module PublishHelper
  # This gets extended in ActiveRecord objects
  
  def published
    self.where(:published => true)
  end
end

app/views/add_ons/_form.html.erb
<%= form_for(@add_on) do |f| %>
  <% if @add_on.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@add_on.errors.count, "error") %> prohibited this add_on from being saved:</h2>

      <ul>
      <% @add_on.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/add_ons/edit.html.erb
<h1>Editing Add On</h1>

<%= render 'form' %>

<%= link_to 'Show', @add_on %> |
<%= link_to 'Back', add_ons_path %>

app/views/add_ons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Add Ons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_ons.each do |add_on| %>
      <tr>
        <td><%= add_on.name %></td>
        <td><%= add_on.price %></td>
        <td><%= add_on.published %></td>
        <td><%= link_to 'Show', add_on %></td>
        <td><%= link_to 'Edit', edit_add_on_path(add_on) %></td>
        <td><%= link_to 'Destroy', add_on, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add on', new_add_on_path %>

app/views/add_ons/new.html.erb
<h1>New Add On</h1>

<%= render 'form' %>

<%= link_to 'Back', add_ons_path %>

app/views/add_ons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @add_on.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @add_on.price %>
</p>

<p>
  <strong>Published:</strong>
  <%= @add_on.published %>
</p>

<%= link_to 'Edit', edit_add_on_path(@add_on) %> |
<%= link_to 'Back', add_ons_path %>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
	<%= error_messages(@menu) %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="form-group">
  	<%= f.label :description %>
  	<%= f.text_area :description %>
  </div>
  
  <div class="form-group">
  	<label>
  		<%= f.check_box :published %>
  		Published?
  	</label>
  </div>
  
  <%= embedded_sections_form(f) %>
  
  <div class="actions">
    <%= f.submit %>
    
    <% unless @menu.new_record? %>
    	<%= link_to 'Destroy', menu_path(@menu), :method => :delete, :data => {:confirm => 'Are you sure? This is PERMANENT!'} %>
    <% end %>
  </div>
<% end %>

<script>
	$(document).ready(function(){
		initializeMenu();
	});
</script>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/parts/_error_messages.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_embedded_form.html.erb
<div class="products">
	<h3>Products</h3>
	<%= form_builder.fields_for :products do |f| %>
		<div class ="product">
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description %>
			</div>
			
			<div class="form-group">
				<label>
					<%= f.check_box :published %>
					Published?
				</label>
			</div>
			
			<div class="form-group">
				<label>
					<%= f.check_box :available %>
					Available?
				</label>
			</div>
			
			<% unless f.object.new_record? %>
				<div class="form-group">
					<label>
						<%= f.check_box :_destroy %>
						Destroy?
					</label>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/sections/_embedded_form.html.erb
<div id="sections">
	<h2>Sections</h2>
	<%= form_builder.fields_for :sections do |f| %>
		<div class="section">
			<%= f.hidden_field :order, :class => 'section_order_field' %>
			
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, :class => 'section_name' %>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description %>
			</div>
			
			
			<div class="form-group">
				<label>
					<%= f.check_box :published %>
					Published?
				</label>
			</div>
			
			<% unless f.object.new_record? %>
				<div class="form-group">
					<label>
						<%= f.check_box :_destroy %> 
						Destroy? 
					</label>
				</div>
			<% end %>
			
			<%= embedded_products_form(f) %>
		</div>
	<% end %>
</div>

<script>
	var all_sections_full = function(){
		var sections = $('.section_name');
		var full = true;
		for(var i = 0; i < sections.length; i++){
			console.log($(sections)[i].val());
			if($(sections)[i].val == ''){
				full = false;
				break
			}
		}
		
		return full;
	}
	
	function addSectionFields(){
		var section = $('.section').first().clone();
		var index = new Date().getTime();
		section.html(section.html().replace(/menu_sections_attributes_\d+_/g, 'menu_sections_attributes_' + index + '_'));
		section.html(section.html().replace(/menu\[sections_attributes\]\[\d+\]/g, 'menu[sections_attributes][' + index + ']'));
		addSectionFieldsIfFull(section);
		$('#sections').append(section);
	}
	
	function addSectionFieldsIfFull(element){
		$(element).focusout(function(){
			if(all_sections_full){
				addSectionFields();	
				orderSections();
				addSectionFieldsIfFull();
			}
		})
	}
	
	
	
	$(document).ready(function(){
		addSectionFieldsIfFull();
	});
	
</script>